"""
Regenerate fixtures/v3_sample.{bin,txt} from the production Python encoder.

The .bin is what the server would send; the .txt is what the values were.
test_protocol.cpp decodes the .bin with the FIRMWARE header and compares.
tests/unit/protocol/test_v3_fixture_current.py fails if the committed .bin
no longer matches the current encoder, so the pair cannot silently drift.

    esurf/bin/python tests/unit/firmware/gen_v3_fixture.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
for p in (os.path.join(ROOT, "cpp_message_wrapper"), os.path.join(ROOT, "web_and_database")):
    if p not in sys.path:
        sys.path.insert(0, p)

SURF = dict(
    wave_period_s=8, wave_height_cm=120, wave_threshold_cm=100,
    wind_speed_mps=5, wind_speed_threshold_knots=15, wind_direction_deg=270,
    stale_data_warning=False, data_available=True, quiet_hours_active=False, off_hours_active=True,
)
SETTINGS = dict(
    led_theme="ocean_sunset", brightness_multiplier=0.3, fetch_interval_ms=780000,
    latitude=32.4425, longitude=34.8683, tz_offset=7200,
)
THEME_INDEX = {"classic_surf": 0, "vibrant_mix": 1, "tropical_paradise": 2, "ocean_sunset": 3, "electric_vibes": 4}


def expected_lines():
    e = {**SURF}
    e = {k: int(v) for k, v in e.items()}
    e["led_theme_index"] = THEME_INDEX[SETTINGS["led_theme"]]
    e["brightness_pct"] = int(SETTINGS["brightness_multiplier"] * 100)
    e["fetch_interval_ms"] = SETTINGS["fetch_interval_ms"]
    e["latitude"] = SETTINGS["latitude"]
    e["longitude"] = SETTINGS["longitude"]
    e["tz_offset"] = SETTINGS["tz_offset"]
    return ["# generated by gen_v3_fixture.py; key=value, consumed by test_protocol.cpp"] + [f"{k}={v}" for k, v in e.items()]


def encode():
    from cpp_encoder import encode_v3_response_cpp
    return encode_v3_response_cpp(SURF, SETTINGS)


def main():
    out = os.path.join(HERE, "fixtures")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "v3_sample.bin"), "wb") as f:
        f.write(encode())
    with open(os.path.join(out, "v3_sample.txt"), "w") as f:
        f.write("\n".join(expected_lines()) + "\n")
    print("wrote fixtures/v3_sample.bin (26 bytes) and fixtures/v3_sample.txt")


if __name__ == "__main__":
    main()
